version: '3'

services:
  app:
    build: .
    sysctls:
      - net.ipv4.tcp_mtu_probing=2
      - net.ipv4.tcp_base_mss=1300
      - net.ipv6.conf.all.disable_ipv6=1
    volumes:
      - gdalwmscache:/gdalwmscache

  web:
    image: nginx:stable
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - app

volumes:
  gdalwmscache:
